// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpqDN7ZZOVbzuh5UDiwxaU4xsPYgqSB8',
    appId: '1:241414160830:web:fbee55498bd11e5c3fb9ef',
    messagingSenderId: '241414160830',
    projectId: 'supa-koto-fbc1a',
    authDomain: 'supa-koto-fbc1a.firebaseapp.com',
    storageBucket: 'supa-koto-fbc1a.appspot.com',
    measurementId: 'G-K2VR1QEXFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnw1ECEYgCPPmMb1iKlrluL8_0CKZlahI',
    appId: '1:241414160830:android:4b0a8a6f2935d62d3fb9ef',
    messagingSenderId: '241414160830',
    projectId: 'supa-koto-fbc1a',
    storageBucket: 'supa-koto-fbc1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5AHfm6cAWxJz9duJ539Z3-CnLgtgy10',
    appId: '1:241414160830:ios:50a133996de8d70b3fb9ef',
    messagingSenderId: '241414160830',
    projectId: 'supa-koto-fbc1a',
    storageBucket: 'supa-koto-fbc1a.appspot.com',
    iosClientId: '241414160830-anrkiri15drb3hs5of7blr5m6o2vfl47.apps.googleusercontent.com',
    iosBundleId: 'com.promina.supakotoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5AHfm6cAWxJz9duJ539Z3-CnLgtgy10',
    appId: '1:241414160830:ios:50a133996de8d70b3fb9ef',
    messagingSenderId: '241414160830',
    projectId: 'supa-koto-fbc1a',
    storageBucket: 'supa-koto-fbc1a.appspot.com',
    iosClientId: '241414160830-anrkiri15drb3hs5of7blr5m6o2vfl47.apps.googleusercontent.com',
    iosBundleId: 'com.promina.supakotoapp',
  );
}
